### ISSUE TITLE
controllers\ReportsController.php#actionMultiplePrescriptions(25)

### ISSUE THREAD

**Issue by ruanceli** [ipti/hb#1]
Números que estão sendo apresentados não são os mesmos dos relatórios, lista de alunos diferentes.

![image](https://cloud.githubusercontent.com/assets/1492822/9467275/e0d0f408-4b10-11e5-9337-a158cfe4e1b9.png)
http://www.hb.ipti.org.br/index.php?r=consultation%2Findex&c=6

![image](https://cloud.githubusercontent.com/assets/1492822/9467262/c6305a3a-4b10-11e5-87ef-287e1d9ccd24.png)
http://www.hb.ipti.org.br/index.php?r=reports%2Fmultiple-prescriptions&cid=6

**Comment by franciscocabral** [comment]
Testado em:
Windows 
FireFox 39 - Work
Chrome 44 - Inconsistente

Debian
Chrome 39 - Work
Chrome 43 - Work
Chrome 45 - Work
FireFox 39 - Work

**Comment by franciscocabral** [comment]
Vou precisar do banco de produção para verificar este caso. Isto não esta acontecendo com o banco de desenvolvimento.

**Comment by ipti** [comment]
Anexo

**Comment by franciscocabral** [comment]
Corrigido. https://github.com/ipti/hb/commit/cb64f245b6dd3878a8f9c210a31f08ff4f52cb87
