### ISSUE TITLE
hb/views/site/index.php#55

### ISSUE THREAD

**Issue by ipti** [ipti/hb#3]
Número estão negativos em algumas campanhas.
![image](https://cloud.githubusercontent.com/assets/1491064/9903135/162ee214-5c4a-11e5-9c88-04b5025a02ce.png)

**Comment by RafaelPedral** [comment]
Os números negativos correspondiam à quantidade de agreed_term duplicados indevidamente para uma dada campanha na tabela hemoglobin.

Corrigido no commit 4d347e5ec0622619b8a670fbfa8e8bdbe9e0403e, mas seria interessante também investigar a causa das duplicatas (se foi erro na importação ou no ato do cadastro) e removê-las do banco.
